apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: pro
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 500m
      nodeSelector:   # Node to POD matching
        nodegroup: front